<?php

declare(strict_types=1);

namespace TestResource\Unit\Eboreum\Exceptional\MethodArgumentDiscloserTest\testGetDefaultValueForReflectionParameterThrowsExceptionWhenClassExistsButClassVariableDoesNotExist;

class ClassExistsButClassConstantBarDoesNotExistA
{
}